// <auto-generated />
using System;
using Assessment5.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment5.Migrations
{
    [DbContext(typeof(PODbContext))]
    [Migration("20240812095958_CreatePODb")]
    partial class CreatePODb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assessment5.Entities.Item", b =>
                {
                    b.Property<string>("ItCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItDesc")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("ItRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItCode");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Assessment5.Entities.POMaster", b =>
                {
                    b.Property<string>("PONo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PODate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SupplierNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PONo");

                    b.HasIndex("ItCode");

                    b.HasIndex("SupplierNo");

                    b.ToTable("POMasters");
                });

            modelBuilder.Entity("Assessment5.Entities.Supplier", b =>
                {
                    b.Property<string>("SupplierNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("SupplierNo");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Assessment5.Entities.POMaster", b =>
                {
                    b.HasOne("Assessment5.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assessment5.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Supplier");
                });
#pragma warning restore 612, 618
        }
    }
}
